server:
  port: 8082

spring:
  application:
    name: event-consumer
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      group-id: opensearch-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      max-poll-records: 50
    listener:
      type: batch

wikimedia:
  kafka.topic: "wikimedia.recentchange"
