server:
  port: 8081

spring:
  application:
    name: event-interceptor
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}

wikimedia:
  sse:
    host: "https://stream.wikimedia.org"
    endpoint: "/v2/stream/recentchange"
  kafka.topic: "wikimedia.recentchange"